### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by Radiergummi** [vabatta/cloudflare-redirector-worker#1]
What does this project actually _do_? The Readme doesn't disclose much. It sounds a bit like what I need, but I'm not sure.  
Maybe you could add a short introduction to the Readme? 🙂

**Comment by vabatta** [comment]
This project uses the https://github.com/vabatta/cloudflare-redirector-worker/blob/master/utils/synchronize.js file to synchronise a Storyblok story with a list of redirections components as described in https://github.com/vabatta/cloudflare-redirector-worker/blob/master/src/types.d.ts#L1 to package them in a javascript worker to have redirections directly on a host level in Cloudflare. 

You can read about the specs and behaviour in https://github.com/vabatta/cloudflare-redirector-worker/blob/master/features/handler.feature and the other feature for a detail description with use cases.

**Comment by Radiergummi** [comment]
I don't know if this is useful to you, but I'll leave it here just in case.  
I solved it a bit differently and chose to generate a `_redirects` file during the Vite build phase:

https://github.com/feinschliff-studio/website/blob/develop/src/build/vite-plugin-storyblok-redirects.mts

It pulls redirect rules from a data source, with the status code added as an optional dimension.

Thank you for the inspiration though, closing this issue 🙂
